
SAVE_CURSOR=$(tput sc)
RESTORE_CURSOR=$(tput rc)
CLEAR_TO_EOL='\033[K'
MOVE_TO_ORIGIN="\033[1;1H"
COLOR_NORMAL='\033[0m'
COLOR_BOLD='\033[1m'
COLOR_GRAY='\033[2m'

unset PROMPT_COMMAND

PS1="\[${SAVE_CURSOR}${MOVE_TO_ORIGIN}${COLOR_GRAY} $RANDOM ${CLEAR_TO_EOL}${RESTORE_CURSOR}\]$ "
